trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
    persistCredentials: true
    fetchDepth: 0

  # Step 1: Deploy to Azure Static Web Apps
  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Azure Static Web Apps'
    inputs:
      app_location: '/'
      output_location: ''
      azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)

  # Step 2: Sync to GitHub Pages
  - script: |
      git config --global user.email "neeraj.ai.agrawal@gmail.com"
      git config --global user.name "Neeraj Agrawal"
      git remote add github https://$(GITHUB_PAT)@github.com/neerajaiagrawal/neerajaiagrawal.github.io.git
      git push github HEAD:main --force
    displayName: 'Sync to GitHub Pages'
